export default{
    'zh':{
        translation:{
            'Minesweeper':'扫雷',
            'New Game':'新游戏',
            'Data Analysis':'数据分析',
            'Settings':'设置',
            'Steps':'步数：',
            'Remain':'剩余雷数：',
            'Failed':'失败了',
            'Succeed':'成功了',
            'Beginner':'初级',
            'Middle':'中级',
            'Expert':'高级',
            'Width':'宽度',
            'Height':'高度',
            'Mines Count':'雷数',
            'OK':'确定',
            'Cancel':'取消',
            'error_width':'宽度值必须为整数',
            'error_height':'高度值必须为整数',
            'error_mines':'雷数必须为整数',
            'Back':'返回',
            'Close':'关闭',
            'Export JSON':'导出JSON数据',
            'Export DBF':'导出DBF数据',
            'Level':'级别',
            'Success Rate':'成功率',
            'Average Steps':'平均步数',
            'Average Time':'平均用时',
            'One-step Success Times':'一步成功次数',
        }
    },
    'en':{
        translation:{
            'Minesweeper':'Minesweeper',
            'New Game':'New Game',
            'Data Analysis':'Data Analysis',
            'Settings':'Settings',
            'Steps':'Steps: ',
            'Remain':'Remain: ',
            'Failed':'Failed',
            'Succeed':'Succeed',
            'Beginner':'Beginner',
            'Middle':'Middle',
            'Expert':'Expert',
            'Width':'Width',
            'Height':'Height',
            'Mines Count':'Mines',
            'OK':'OK',
            'Cancel':'Cancel',
            'error_width':'Width must be integer',
            'error_height':'Height must be integer',
            'error_mines':'Mines must be integer',
            'Back':'Back',
            'Close':'Close',
            'Export JSON':'Export As JSON',
            'Export DBF':'Export As DBF',
            'Level':'Level',
            'Success Rate':'Success Rate',
            'Average Steps':'Avg. Steps',
            'Average Time':'Avg. Time',
            'Average Time':'Avg. Time',
            'One-step Success Times':'One-step Success Times',
        }
    },
    'ja':{
        translation:{
            'Minesweeper':'マインスイーパ',
            'New Game':'スタート',
            'Data Analysis':'データ解析',
            'Settings':'設定',
            'Steps':'操作回数：',
            'Remain':'残り地雷：',
            'Failed':'失敗しました',
            'Succeed':'成功しました',
            'Beginner':'初級',
            'Middle':'中級',
            'Expert':'上級',
            'Width':'幅',
            'Height':'高さ',
            'Mines Count':'地雷の数',
            'OK':'OK',
            'Cancel':'キャンセル',
            'error_width':'幅は整数でなければなりません',
            'error_height':'高さは整数でなければなりません',
            'error_mines':'地雷の数は整数でなければなりません',
            'Back':'戻る',
            'Close':'閉じる',
            'Export JSON':'JSONをエクスポート',
            'Export DBF':'DBFをエクスポート',
            'Level':'レベル',
            'Success Rate':'成功率',
            'Average Steps':'平均操作回数',
            'Average Time':'平均時間',
            'One-step Success Times':'一回の操作で成功できるの回数',
        }
    }
}